// Objective-C API for talking to github.com/zemirco/todo/item Go package.
//   gobind -lang=objc github.com/zemirco/todo/item
//
// File is generated by gobind. Do not edit.

#ifndef __GoItem_H__
#define __GoItem_H__

#include <Foundation/Foundation.h>

@class GoItemTodo;

@interface GoItemTodo : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)id;
- (void)setID:(NSString*)v;
- (NSString*)rev;
- (void)setRev:(NSString*)v;
- (NSString*)type;
- (void)setType:(NSString*)v;
- (NSString*)text;
- (void)setText:(NSString*)v;
- (double)createdAt;
- (void)setCreatedAt:(double)v;
- (BOOL)done;
- (void)setDone:(BOOL)v;
- (NSString*)awesome;
- (void)setAwesome:(NSString*)v;
- (NSString*)getID;
- (NSString*)getRev;
@end

FOUNDATION_EXPORT GoItemTodo* GoItemNewTodo(NSString* text);

#endif
